
const wheelData = {
  "segmentValuesArray" : [],
  "colorArray":[ "#82BFFF"],
  "svgWidth": 1024,
  "svgHeight": 1024,
  "wheelStrokeColor": "rgba(229,242,255, 1)",
  "wheelStrokeWidth": 65,
  "wheelSize": 900,
  "wheelTextOffsetY": 120,
  "wheelTextColor": "#fff",
  "wheelTextSize": "32px",
  "wheelImageOffsetY": 40,
  "wheelImageSize": 50,
  "centerCircleSize": 280,
  "centerCircleStrokeColor": "rgba(255,255,255, .4)",
  "centerCircleStrokeWidth": 135,
  "centerCircleFillColor": "#fff",
  "centerCircleImageUrl":"",
  "centerCircleImageWidth":500,
  "centerCircleImageHeight":500,
  "segmentStrokeColor": "rgba(255,255,255, .2)",
  "segmentStrokeWidth": 4,
  "centerX": 535,
  "centerY": 535,
  "hasShadows": false,
  "numSpins": 1,
  "spinDestinationArray":[],
  "minSpinDuration": 1,
  "gameOverText":" Game Over :)",
  "invalidSpinText":"INVALID SPIN. PLEASE SPIN AGAIN.",
  "introText":"",
  "hasSound":true,
  "gameId":"9a0232ec06bc431114e2a7f3aea03bbe2164f1aa",
  "clickToSpin": true,
  "spinDirection":"cw"
};

export default wheelData;
